services:
  - type: web
    name: shopping-lens
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      apt-get update && apt-get install -y \
        python3-opencv \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev
      pip install -r requirements.txt
      mkdir -p shopping_lens/data/test_images
      mkdir -p shopping_lens/data/index
      cp -r shopping_lens/data/index/* shopping_lens/data/index/
      mkdir -p /opt/render/.cache/torch/hub/checkpoints
      python -m shopping_lens.scripts.download_models
      python -m shopping_lens.scripts.download_test_images
    startCommand: uvicorn shopping_lens.api.main:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: .
      - key: DEBIAN_FRONTEND
        value: noninteractive
      - key: LOG_LEVEL
        value: DEBUG
      - key: TORCH_HOME
        value: /opt/render/.cache/torch
      - key: TRANSFORMERS_CACHE
        value: /opt/render/.cache/huggingface
      - key: HF_HOME
        value: /opt/render/.cache/huggingface
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: false
    disk:
      name: data
      mountPath: /opt/render/project/src/shopping_lens/data
      sizeGB: 1 