services:
  - type: web
    name: shopping-lens
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn shopping_lens.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 